<?php

namespace App\Models;

use CodeIgniter\Model;

/**
 * Model for the `taxon_media_variants` table.
 *
 * Represents one derived/resized rendition (identified by `variant_key`,
 * e.g. a thumbnail size) of a {@see TaxonMediaModel} original. Variants are
 * generated by {@see \App\Services\TaxonMediaUploadService} and rebuilt in
 * bulk by the `taxon-media:rebuild-variants` command
 * ({@see \App\Commands\RebuildTaxonMediaVariants}), and read alongside their
 * parent media row by {@see \App\Services\TaxonMediaReadService}.
 */
class TaxonMediaVariantModel extends Model
{
    /**
     * @var string
     */
    protected $table = 'taxon_media_variants';

    /**
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * @var string
     */
    protected $returnType = 'array';

    /**
     * @var bool No `updated_at` column; variants are immutable once generated
     *      (a changed variant is rebuilt as a new row rather than edited in place).
     */
    protected $useTimestamps = false;

    /**
     * Mass-assignable columns.
     *
     * - `taxon_media_id` Owning {@see TaxonMediaModel} record this variant was derived from.
     * - `variant_key`    Identifier for the rendition (e.g. thumbnail/original size).
     * - `storage_path`   Path to the stored variant file.
     * - `mime_type`      MIME type of the variant file.
     * - `bytes`          Variant file size in bytes.
     * - `width`          Variant width in pixels.
     * - `height`         Variant height in pixels.
     * - `created_at`     Included here (rather than via `$useTimestamps`) because it must be
     *                    settable explicitly when variants are bulk-rebuilt.
     *
     * @var array<int, string>
     */
    protected $allowedFields = [
        'taxon_media_id',
        'variant_key',
        'storage_path',
        'mime_type',
        'bytes',
        'width',
        'height',
        'created_at',
    ];
}
